---
title: "Finance with R"
output: html_notebook
---

<hr>
1. A one year financial model: *sales - variable costs - fixed costs - taxes = net result*

```{r}
# Turn off scientific notation
options(scipen=999)

# Define starting values
t <- 0
sales <- 1000000
varcosts <- sales * 0.7
fixcosts <- 50000
bresult <- sales - varcosts - fixcosts
taxes <- bresult * 0.25
nresult <- bresult - taxes

finres <- data.frame(t, sales, varcosts, fixcosts, bresult, taxes, nresult)
finres
```

<hr>
2. A 10 year projection with growth rate

```{r, message=FALSE, warning=FALSE}
# Define a function for calculating growing end values
growthcalc <- function(startvalue, rate) {
  
  endvalue <- startvalue * (1 + rate)
  return(endvalue)
  
}

# Calculate a growing independent series and combine them in data frame
growth <- 0.15
inflation <- 0.012

for (s in c(1:10)) {
  
  t <- c(t, s)
  sales <- c(sales,
             growthcalc(sales[s],
                        growth)
             )
  fixcosts <- c(fixcosts,
                growthcalc(fixcosts[s],
                           inflation)
                )
  
}

finres <- data.frame(t, sales, fixcosts)

# Calculate dependent series
library(dplyr)
finres <- mutate(finres,
                 varcosts = sales * 0.7,
                 bresult = sales - varcosts - fixcosts,
                 taxes = bresult * 0.25,
                 nresult = bresult - taxes
                 )

# Plot series
library(ggplot2)
ggplot(finres, aes(x = t, y = nresult)) +
  geom_col(fill = rainbow(max(t)+1)) +
  theme(legend.position="none")
  
```

<hr>
3. A 10 year projection with risky growth rates

```{r}
# Define starting values
t <- 0
sales <- 1000000
fixcosts <- 50000

# Calculate a growing independent series and combine them in data frame with uncertainty
stdevg <- 0.20
stdevi <- 0.005

for (s in c(1:10)) {
  
  t <- c(t, s)
  sales <- c(sales,
             growthcalc(sales[s],
                        rnorm(1, mean = growth, sd = stdevg)
                        )
             )
  fixcosts <- c(fixcosts,
                growthcalc(fixcosts[s],
                           rnorm(1, mean = inflation, sd = stdevi)
                           )
                )
  
}

finres.uncertain <- data.frame(t, sales, fixcosts)

# Calculate dependent series
finres.uncertain <- mutate(finres.uncertain,
                 varcosts = sales * 0.7,
                 bresult = sales - varcosts - fixcosts,
                 taxes = bresult * 0.25,
                 nresult = bresult - taxes
                 )

# Plot series
ggplot(finres.uncertain, aes(x = t, y = nresult)) +
  geom_col(fill = heat.colors(max(t)+1)) +
  theme(legend.position="none")

```

<hr>
4. Net present value calculations

```{r}
# Function for calculating present values
presval <- function(futurevalue, discountrate, nperiods) {
  
  presentvalue <- futurevalue / (1 + discountrate)^nperiods
  
}

# Calculate present values of net results and add to data frame
discrate <- 0.05
finres.uncertain <- mutate(finres.uncertain,
                 nresult.pres = presval(nresult, discrate, t)
                 )

finres.uncertain

investment <- 3000000
netpresval <- -investment + sum(finres.uncertain$nresult.pres)
```

The resulting Net Present Value equals: **`r round(netpresval)`**

<hr>
5. A 10 year projection with a set of growth rates

```{r, message=FALSE, warning=FALSE}
# Define starting values
t <- 0
sales <- 1000000
fixcosts <- 50000
# Define a function for calculating growing end values

# Calculate a growing independent series and combine them in data frame
growth <- c(rep(0.15, 8), rep(0, 2))
inflation <- 0.012

for (s in c(1:10)) {
  
  t <- c(t, s)
  sales <- c(sales,
             growthcalc(sales[s],
                        growth[s])
             )
  fixcosts <- c(fixcosts,
                growthcalc(fixcosts[s],
                           inflation)
                )
  
}

finresa <- data.frame(t, sales, fixcosts)

# Calculate dependent series
library(dplyr)
finresa <- mutate(finresa,
                 varcosts = sales * 0.7,
                 bresult = sales - varcosts - fixcosts,
                 taxes = bresult * 0.25,
                 nresult = bresult - taxes
                 )

# Plot series
library(ggplot2)
ggplot(finresa, aes(x = t, y = nresult)) +
  geom_col(fill = topo.colors(max(t)+1)) +
  theme(legend.position="none")
```